// DO NOT EDIT. generated by webtyp.com/ormc

package sse

import (
	"webtyp.com/model"
)

type SSEMessage struct {
	Id string
	Event string
	Data []byte
}

func (m *SSEMessage) ModelName() string { return "ssemessage" }

func (m *SSEMessage) Schema() []model.Field { return SSEMessageModel.Fields }

func (m *SSEMessage) Pointers() []any { return []any{&m.Id, &m.Event, &m.Data} }

func (m *SSEMessage) IsNil() bool { return m == nil }

func (m *SSEMessage) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("event", m.Event)
	w.Bytes("data", m.Data)
}

func (m *SSEMessage) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("event"); ok { m.Event = v }
	if v, ok := r.Bytes("data"); ok { m.Data = v }
}

type SSEMessageList []*SSEMessage

func (s *SSEMessageList) Schema() []model.Field { return nil }
func (s *SSEMessageList) Pointers() []any     { return nil }
func (s *SSEMessageList) Len() int             { return len(*s) }
func (s *SSEMessageList) At(i int) model.Fielder { return (*s)[i] }
func (s *SSEMessageList) Append() model.Fielder  { v := &SSEMessage{}; *s = append(*s, v); return v }
func (s *SSEMessageList) IsNil() bool          { return s == nil }
func (s *SSEMessageList) EncodeFields(_ model.FieldWriter) {}
func (s *SSEMessageList) DecodeFields(_ model.FieldReader) {}

func (m *SSEMessage) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

